server:
  port: 1002

spring:
  application:
    name: spring-cloud-basic
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

#eureka
eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://sdpeer1:8761/eureka


# actuator 微服务健康监控
# 项目启动后 可以使用 ip:port/actuator/{"beans","caches","health","info","mappings","scheduledtask"}等等查看此服务健康信息
# 详情参照：https://www.cnblogs.com/baidawei/p/9183531.html
info:
  head: head
  body: body
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false

#断路由
feign:
  hystrix:
    enabled: true

