server:
  port: 1002
  servlet:
    context-path: /spring/cloud/basic

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
  # spring cloud bus config
#  cloud:
#    bus:
#      trace:
#        enabled: true
#      enabled: true