server:
  port: 8763
eureka:
  instance:
    #服务器运行的宿主及其名称
    hostname: sdpeer3
  client:
    #是否注册到eureka
    register-with-eureka: true
    #是否检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://sdpeer1:8761/eureka,http://sdpeer2:8762/eureka
  server:
    #在Eureka服务器获取不到集群里对等服务器上的实例时，需要等待的时间，单位为毫秒
    wait-time-in-ms-when-sync-empty: 5
