server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zhangzhiyuan12580/git.git
          username: 825065254@qq.com
          password: 206918zz.
    bus:
      enabled: true
      trace:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
